# Técnicas e Instrumentación en Psicofisiología
Elaborado por el Mtro. Angel Jacobo para la Facultad de Medicina y Psicología, Universidad Autónoma de Baja California.

# Práctica 1: Ambientes de desarrollo, Python, variables y manejo general de datos

Durante esta práctica, el alumno aprenderá aspectos básicos relacionados con el uso de lenguajes de programación para la automatización de distintos procedimientos. Específicamente, se trabajará con el lenguaje de programación Python, un lenguaje versátil que se ha convertido en un estándar para el análisis de datos en distintos campos.


## Sección 1. Sobre ambientes de desarrollo
Todas las prácticas serán resueltas utilizando cuadernos Jupyter. Jupyter es un ambiente de desarrollo: software especializado para efectuar proyectos de programación. Para facilitar la realización de ejercicios, los cuadernos Jupyter permiten la ejecución de bloques de código independientes sin la necesidad de finalizar absolutamente toda la redacción. 

Los bloques de código deben ser escritos dentro de una *celda* como la de abajo.


In [ ]:
# Hola, yo soy una celda

En la celda de arriba, notará usted que el texto fue escrito con una # a la izquierda. Esto significa que en esa *línea* se ha escrito un *comentario.* Un comentario es una línea en medio del código que la computadora no leerá como parte del mismo. Es muy útil para describir el comportamiento del código que hemos escrito, para que otras personas puedan usarlo también.

Similarmente, note que este bloque de texto y la celda con el comentario tienen diferente clasificación de acuerdo con Jupyter. Esta celda es de tipo *Markdown* y la celda de arriba es de tipo *Code.*

Solamente las celdas de tipo Code ejecutarán código y se sujetarán a las restricciones que demanda el lenguaje de programación.


#### Ejercicio 1.1 ---------------------------------------------------------------------------------------
Pruebe a ejecutar la celda siguiente (seleccionando la celda y haciendo click en el botón de reproducir, el triangulito) para ver lo que sucede.

In [44]:
# Hola, yo soy un comentario
print("Y yo soy código")

Y yo soy código


Si debajo de la celda aparece el texto "Y yo soy código," ¡Felicidades! Ha ejecutado su primer programa.

#### Ejercicio 1.2 ---------------------------------------------------------------------------------------

Ahora convierta la línea de código adelante (la función print) también en un comentario, y ejecute la celda. 

Después explore el comportamiento de las celdas siguientes.

In [48]:
# Hola, yo soy un comentario
#print("Conviérteme a mí también!")

¡No debe pasar nada! Porque no hay nada qué hacer. Si no hay código en la celda que PIDA la aparición de algo en la pantalla, no hay una *salida.* 



In [ ]:
# En algunos casos una línea puede tener el comportamiento de imprimir en pantalla de forma implícita,
# pero permanecerá únicamente el resultado de la última línea que lo solicite:
1+1
2+2

In [ ]:
# Y en otros casos, puede resultar en un error:
2/0

## Sección 2. Básicos sobre Python

Como se menciona más arriba, Python es un lenguaje de programación áltamente versátil. Un lenguaje de programación es "el idioma" que utilizamos para darle instrucciones a una computadora. Estas instrucciones eventualmente son convertidas a secuencias de impulsos eléctricos que viajan por los circuitos físicos de la computadora y resultan en los efectos deseados. 

Mientras más explícito tenga que ser un lenguaje de programación respecto de su uso de los circuitos físicos, decimos que es de **más bajo nivel.** Los lenguajes de bajo nivel suelen tener una gran velocidad de ejecución, pero son difíciles de entender por los humanos. Lenguajes como *Ensamblador*, y hoy en día, *C* son considerados lenguajes de bajo nivel. 

Python (junto a R, C++ y Julia) es considerado un lenguaje de **bastante alto nivel**, ya que no pide del usuario conocer las características específicas del dispositivo con el que se está trabajando. El manejo de memoria y conjuntos de instrucciones ocurre de forma automática. Es decir, Python es relativamente fácil de aprender y de usar, en parte por eso es tan popular.


### Cadenas
Ahora bien, en la sección anterior usted tuvo su primer contacto con instrucciones usando Python, cuando llamó la función print() y al tratar de hacer aritmética. Eso fue un poco aventurado, ya que no hemos hablado ni siquiera de por qué hubo que usar comillas ("") para imprimir el texto.

Verá usted. Existen diferentes tipos de datos, y en ocasiones Python requiere que esos tipos sean indicados de forma explicita, para evitar ambigüedades y errores. 

Usamos las comillas para señalar que lo que hay dentro es una *cadena (string)*: una serie de caracteres que NO deben ser leídos como código ni cualquier otra cosa. En Psicofisiología, el uso más frecuente de las cadenas es contener datos **nominales** como nombres, ciudades de origen, descripciones médicas y demás.

#### Ejemplo 2.1

In [51]:
"Como esto"

'Como esto'

In [50]:
No como esto

SyntaxError: invalid syntax (3720365954.py, line 1)

### Números

Otros datos que usaremos con frecuencia son los de tipo *numérico*. Estos pueden ser *enteros* si no tienen una parte fraccionaria, o *racionales* si sí la tienen. En Python, ambas categorías se tratan como tipos de datos distintos. Los *enteros* son de tipo *integer*, mientras que los *racionales* son de tipo *float*. Ambos tipos pueden usarse para realizar operaciones aritméticas.

En Psicofisiología, con frecuencia usamos los enteros para representar **categorías**, como condiciones experimentales, grupos de edad, cohortes, o diagnósticos. Aunque no es raro utilizarlos también en registros de frecuencia conductual.

Por otro lado, usamos los racionales para representar **mediciones fisiológicas**: señales de electroencefalografía, magnetoencefalografía, electromiografía, fuerza de contracción, espirometría, entre otras. 

A menudo los registros fisiológicos consisten de largas series de floats individuales que forman una *serie de tiempo.*

#### Ejemplo 2.2
Puede usarse la función type() para explorar el tipo que se le ha asignado a un dato. 

Note que aunque para un ser humano "1" y 1 puedan dar la misma información, no es el mismo tipo de dato para Python.

In [52]:
type("1")

str

In [53]:
type(1)

int

In [54]:
type(1.1)

float

## Sección 3. Asignación de variables y contenedores

Para facilitar la manipulación de datos y poder conservarlos más allá de la celda donde ejecutamos un bloque de código, tenemos que utilizar *variables.* Una variable es un "nombre" al que podemos asignarle algún dato o conjunto de datos. Utilizar el nombre de la variable nos permite escribir código más compacto y fácil de leer.

En Python, para asignar datos a una variable usamos el operador **=**

Es muy importante recordar que dentro de nuestro código ese operador es una indicación de *escribir* dentro de la variable; NO es un indicador de "igual."

#### Ejemplo 3.1

In [55]:
# Podemos, por ejemplo, asignar una oración completa a una variable:

cadena = "He escuchado últimamente que ciertas galletas saladas son horneadas, aunque desconozco cuál es la verdad."

# Ejecutar la celda no tendrá una salida visible, porque no estamos solicitando una impresión.

In [56]:
# Sin embargo, si pedimos la impresión de la variable...

print(cadena)

He escuchado últimamente que ciertas galletas saladas son horneadas, aunque desconozco cuál es la verdad.


...Nos muestra el contenido.

#### Ejercicio 3.1 ---------------------------------------------------------------------------------------
Pruebe a asignar diferentes datos numéricos a distintas variables, y después trate de realizar operaciones aritméticas, guardando el resultado en una nueva variable.

Sustituya los guiones de la siguiente celda por cualquier nombre que se le ocurra para sus variables. (Si lo desea, agregue más líneas)


Después, imprima su variable resultado en la celda restante.

In [ ]:
__ = 
__ =
__ = __ * __

## Estructuras de datos
Así como existen tipos de datos que podemos guardar dentro de variables, existen también objetos donde podemos guardar múltiples variables. A estos objetos los llamamos *estructuras de datos*, aunque también se les puede conocer como **contenedores**.

En Psicofisiología con Python, los contenedores que utilizamos con más frecuencia son las **listas**, los **diccionarios**, y los **arreglos**.


#### Ejemplo 3.2

Las **listas** son contenedores que pueden incluir objetos de esencialmente cualquier tipo dentro de sí. Es posible, de hecho, guardar una lista dentro de otra lista. Es parecido a tener en casa una bolsa para las bolsas. La diferencia aquí es que una lista puede contener un conjunto virtualmente infinito de objetos.


Para indicarle a Python que necesitamos una lista, utilizamos *corchetes (square brackets)* [ ] ; dentro de los cuales podemos guardar tanto datos crudos como variables previamente asignadas. Para distinguir entre objetos, usamos comas  ,

In [ ]:
lista_ejemplo = ["1", 1, 1.1]
print(lista_ejemplo)

Una vez que hemos generado una lista, podemos referirnos a objetos dentro de la misma utilizando *índices (singular, index; plural, indices)*.

Si abrimos corchetes a la derecha del nombre de nuestra lista e insertamos un número entero, Python sabrá que nos referimos al objeto que se encuentra en esa posición. 

Es importante señalar que los órdenes de las listas asignan la primera posición al número **0**.

In [ ]:
# De manera que si quiero imprimir únicamente el primer objeto, lo hago de esta manera:
print(lista_ejemplo[0])

In [ ]:
# Puedo tener una lista de listas de esta manera:
lista_listas = [lista_ejemplo, lista_ejemplo, lista_ejemplo]

# Y si quiero imprimir el primer objeto de la primera lista, lo haría así:

print(lista_listas[0][0])

#### Ejemplo 3.3
Aunque las listas pueden utilizarse para muchísimas tareas, también nos son de utilidad los **diccionarios**. Estos contenedores se caracterízan por guardar objetos utilizando claves en específico. Mientras que necesariamente utilizamos índices para navegar una lista, una clave puede ser cualquier número o cadena de texto. Los diccionarios son especialmente útiles cuando se trabaja con bases de datos particularmente grandes, y son groseramente equivalentes a los *libros de códigos* que se utilizan en investigaciones de lápiz y papel.

Para asignar a una variable el tipo diccionario, es necesario utilizar los símbolos llaves { } , e incluir los pares de claves y contenido en la misma:

In [ ]:
dict_ejemplo = {'je':'UEJEJE???!??!?!?', 'jo':'jojjojoooo', 'ji':'tomate'}

Note que la gramática es clave:contenido ; y que para diferenciar entre cada par es suficiente utilizar comas.

In [ ]:
print(dict_ejemplo['je'])

#### Ejercicio 3.2 ----------------------------------------------------------------------------------------------------

Para estas alturas seguro empieza a acostumbrarse al ambiente de desarrollo. Durante este ejercicio, añada las celdas que considere conveniente. Recuerde que puede volver a ejecutar la misma celda con diferente contenido, si quiere explorar un poco.

**Instrucciones:** 


**A.** 

Asigne nueve nuevas variables con los datos que usted quiera (pero que sean diferentes). Después cree tres listas, guardando tres variables en cada lista.

Logrado lo anterior, imprima el tercer objeto de la segunda lista.

**B.** 

Asigne esa última variable como llave en un diccionario, con el contenido siendo el primer objeto de la primera lista creada en el apartado A. 

Imprima el resultado de usar la clave con su diccionario.

In [59]:
# A.

In [60]:
# B.

2


## Arreglos y bibliotecas
Estrictamente hablando, las listas pueden entenderse como arreglos en otros lenguajes de programación, aunque poseen algunas particularidades curiosas. De cualquier manera, para nosotros los **arreglos (arrays)** son contenedores con dimensiones particulares homogéneas, que están optimizados para el trabajo con tipos de datos con formatos específicos. 

Para cómputo científico, a menudo dependeremos de *bibliotecas (libraries)*: Conjuntos de código pre-escrito que podemos utilizar con libertad para evitar "re-inventar la rueda." Algunas bibliotecas importantes que se emplean con frecuencia en Psicofisiología son **Numpy** y **PyTorch** (además de muchísimas otras, pero lo dejaremos para otro día). Estas bibliotecas introducen implementaciones propias para sus arreglos, para poder realizar cálculos con mayor velocidad.

Para invocar el uso de una biblioteca, y obtener acceso al código que contiene, utilizaremos la palabra clave *import* de la siguiente manera:

In [ ]:
import numpy

De ahora en adelante, cuando queramos utilizar código de la biblioteca Numpy, escribiremos su nombre, seguido por un punto y el nombre de lo que queremos usar (una función, un objeto). Es a esto que le llamamos una *invocación (invocation)* o *llamada (call)*. 



Al programar, a veces ayuda imaginarse que usted es alguna suerte de practicante de magia, y que debe solicitar el apoyo de entidades poderosas para realizar milagros. 

Ya sabe, como sumar dos números o algo así.

![alt text](woosh.jpg "michibrujo")

#### Ejemplo 3.4

In [ ]:
# Para facilitar las invocaciones, puede asignarse un alias a una biblioteca de esta forma:
import numpy as np
# En adelante, será suficiente escribir con el siguiente formato: np.loquequeremosdenumpy

Ahora crearemos una *matriz (matrix).* Las matrices son objetos matemáticos de tamaño mxn que podríamos describir como equivalentes a las tablas. Tienen propiedades matemáticas que las vuelven increíblemente útiles en Ciencia Cognitiva (pero de nuevo, es para otro día).

Para nuestra implementación, utilizaremos una lista de listas que será convertida en un arreglo de Numpy mediante la función asarray().

In [61]:
matriz_ejemplo = np.asarray([[1,2,3],[4,5,6],[7,8,9]])
print(matriz_ejemplo, type(matriz_ejemplo))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


Note que lo anterior es posible ÚNICAMENTE porque las tres listas son del mismo tamaño.

Si no es el caso...

In [62]:
matriz_fea = np.asarray([[1,2,3],[4,5,6,7],[8,9,10]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

...Obtendremos un error.